// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYfWg9mR9f9yVn9BpEtTQVKbrAEpKjPI',
    appId: '1:980052399235:web:595dc998a39804c31337b6',
    messagingSenderId: '980052399235',
    projectId: 'green-file-6e537',
    authDomain: 'green-file-6e537.firebaseapp.com',
    storageBucket: 'green-file-6e537.appspot.com',
    measurementId: 'G-TL4YD1VNSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7fFTFUvvtTl9CH8B_fv3UQ58zFFMUOk',
    appId: '1:980052399235:android:08baa5d3f0f6a9661337b6',
    messagingSenderId: '980052399235',
    projectId: 'green-file-6e537',
    storageBucket: 'green-file-6e537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNHbbNBCPv71ygakSz6ZbLpJkcW5NVa0',
    appId: '1:980052399235:ios:fa9312f238a2d38b1337b6',
    messagingSenderId: '980052399235',
    projectId: 'green-file-6e537',
    storageBucket: 'green-file-6e537.appspot.com',
    iosBundleId: 'com.example.greenFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNHbbNBCPv71ygakSz6ZbLpJkcW5NVa0',
    appId: '1:980052399235:ios:fa9312f238a2d38b1337b6',
    messagingSenderId: '980052399235',
    projectId: 'green-file-6e537',
    storageBucket: 'green-file-6e537.appspot.com',
    iosBundleId: 'com.example.greenFile',
  );
}
