// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9z9Nxeb8ca3HDe4E2ZsZ9JCswCE0sO08',
    appId: '1:515977321779:web:53c2976b7f355201edb246',
    messagingSenderId: '515977321779',
    projectId: 'green-file-aca8b',
    authDomain: 'green-file-aca8b.firebaseapp.com',
    storageBucket: 'green-file-aca8b.appspot.com',
    measurementId: 'G-J9Y346WJ87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrKGvyykG_ZbxNu78FjT7C-cNB5DmDmg',
    appId: '1:515977321779:android:5d508931f1b5b2e4edb246',
    messagingSenderId: '515977321779',
    projectId: 'green-file-aca8b',
    storageBucket: 'green-file-aca8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxokAATDjYYw7aUvUKoevBO9tmJ7TSDNQ',
    appId: '1:515977321779:ios:01f8019670c2df70edb246',
    messagingSenderId: '515977321779',
    projectId: 'green-file-aca8b',
    storageBucket: 'green-file-aca8b.appspot.com',
    iosBundleId: 'com.example.greenFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxokAATDjYYw7aUvUKoevBO9tmJ7TSDNQ',
    appId: '1:515977321779:ios:01f8019670c2df70edb246',
    messagingSenderId: '515977321779',
    projectId: 'green-file-aca8b',
    storageBucket: 'green-file-aca8b.appspot.com',
    iosBundleId: 'com.example.greenFile',
  );
}
